version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Todo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uqm9fsf0te21"
s3_prefix = "Todo"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

